# -*- coding: utf-8 -*-
"""generate_remit_data.py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uWVYAK8hwvssDJ3FowRM7SyuDYTfEn9H
"""

import pandas as pd
import numpy as np

# 1. Load data, keeping leading zeros safe
cms_df = pd.read_csv('MUP_INP_RY25_P03_V10_DY23_PrvSvc.CSV', encoding='cp1252', dtype={'Rndrng_Prvdr_CCN': str, 'DRG_Cd': str})

# NO FILTERING - Processing the entire national dataset (200,000+ rows)
client_df = cms_df.copy()

# 2. Calculate expected payment per DRG batch
client_df['Expected_Total_Payment'] = client_df['Tot_Dschrgs'] * client_df['Avg_Tot_Pymt_Amt']

# 3. Create the bank feed AT THE BATCH LEVEL
bank_feed = client_df[['Rndrng_Prvdr_CCN', 'DRG_Cd', 'Expected_Total_Payment']].copy()

# 4. THE ENTERPRISE FIX: Create the Unique Composite Key
# This glues the Hospital ID and DRG code together (e.g., "010001-291")
bank_feed['Bank_Batch_ID'] = bank_feed['Rndrng_Prvdr_CCN'] + "-" + bank_feed['DRG_Cd']

bank_feed.rename(columns={
    'Expected_Total_Payment': 'Deposit_Amount'
}, inplace=True)

# 5. Inject 1.5% fee variance into 20% of rows nationwide
np.random.seed(42)
variance_mask = np.random.rand(len(bank_feed)) < 0.20
bank_feed.loc[variance_mask, 'Deposit_Amount'] = bank_feed.loc[variance_mask, 'Deposit_Amount'] * 0.985

# 6. Delete 50 random rows entirely to test "Escalate - No Deposit" logic
drop_indices = np.random.choice(bank_feed.index, 50, replace=False)
bank_feed = bank_feed.drop(drop_indices)

# Clean up the export to only show the Key and the Money
bank_feed = bank_feed[['Bank_Batch_ID', 'Deposit_Amount']]

# Export the massive national file
bank_feed.to_csv('Mock_Bank_Feed_National.csv', index=False)
print(f"National Bank feed generated successfully with {len(bank_feed)} batches.")